# Generated by Django 5.0.7 on 2024-08-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
